before_script:
- npm install -g karma
script:
- npm run test-ci
language: node_js
node_js:
- 10
branches:
  only:
  - master
  - develop
notifications:
  slack:
    secure: j9hnkzXbc6IA87N+sInh/YLt1E7GVRIoclQesNWA8eJHrqkJLPsWbY9u4XCYQ8F01H0mE7bTmgvszRsCsb+2Xwn6yxNP4zqiEmAyp0F2NXfAruOOzyIQuUhD9vAIUzy56Opn3c9KEVJbkd4MefxqDCf714uZZ0B6sAMqyX8VX1zZcR3JQbBR6qKJW1krP8RMrnSlshaGZq7odLAsAuhU7km7KEzSoAuVIyB2ieLhq1Hmc+s3wJyEWDOWevi6hjNn798vHnjAhmEtAY1d/eYcE/nt59pXRDijfZdKnaOZ0kMDSRDtZH2O4d4dt8q59mG9n9Az5uxfiCPD2hrsaiJTYrwqRSTP/Xvp7V4tMEnSuyolyAq6aH9N9JhbcRRjD34ZeWf1BhDIXymuWyqagMF/gTEJhy49GQndqZyYyiiKQt6K0qC9woZLaS38eHFm8aymGP0cNsy5Vi8o6Z74ptxMcO9k14NrjxMo1OhMm4zE3upLTHRuJy/39aBgXIxFTwq7wRlApE3tm3vWeSheqJc36D5Takkj2pqyVJzp8o/uaTm2NexFBLRJ7u0mvfJJHj8MiOhRJmc+H/gTmy4oU2/k9DYFLCAaL7v7E+fLfO7HvEmUWCOcGIYbZcfmg0pUJ7EYeN0+tprCEruXfpmxDQ8FINkGINgGJxlWxzPHiWVDWrw=
